baseurl = "https://tengio.gihub.io/"
languageCode = "en-us"
title = "Tengio | We love Open Source"

[params]
  name = "Luigi Agosti, Akshay Dashrath"
  description = "Tengio."
  analytics = "UA-67184502-2"

  [params.projects]
      headline = "projects & demos"

    [[params.projects.list]]
       link = "https://github.com/Tengio/cpn"
       title = "CPN"
       description = "This is a small library that wraps Google Cloud Messaging and add support for in app notification."

    [[params.projects.list]]
       link = "https://github.com/Tengio/tengio.com"
       title = "tengio.com"
       description = "Tengio company website. A clean, simple and flexible website using hugo static generator engine."
